### PR TITLE
conform to RFC 4514 by supporting all required distinguished name attribute types

### PR DESCRIPTION
**Pull request by hannesm**
- STREET was missing
- stateorprovince is usually ST, not SP
- UID was missing

//cc @paurkedal

### CODE REVIEW

**Comment by hannesm** [comment]
and while looking into rfc 4519 i discover that each attributetype also may define their comparison method (octet string / case insensitive / bitmap / ...) - ignoring this for now

**Comment by paurkedal** [comment]
Yes, I think it is good to add the attributes types commonly seen in certificates. I don't think we want to start supporting full schema loading, as that would bring in enough complexity to deserve it's own library.

If we want to do parsing in the current version, I think we would have to reject DNs containing unknown attributes, as we don't know their OID or type. One way to support it though, would be to add the ability for client to provide their own lookup function, or maybe register mappings into a hash table.

**Comment by hannesm** [comment]
note: if you agree with this @paurkedal I'd merge and cut a release of x509

> add the attributes types commonly seen in certificates

do you see after this anything else missing?

> If we want to do parsing .. provide their own lookup function .. register mappings into a hash table

I'd prefer to avoid a parser for the string representation unless we really need to. so far, I only programmatically create the DNs for subject and issuer...

**Comment by paurkedal** [comment]
One thing, do you have a policy for naming the constructors for the attribute types?  I'm looking at the core.schema from our LDAP server, and it defines the name of 0.9.2342.19200300.100.1.1 as either `uid` or `userid` rather than `user_id`.

**Comment by hannesm** [comment]
> policy for naming the constructors for the attribute types?

no, usually I go to e.g. https://www.alvestrand.no/objectid/0.9.2342.19200300.100.1.html to figure out the name and details. OIDs names are usually in camelCase (reorder to camel_case, i.e. replace `C` with `_c`), name the OID value in registry this way, and the constructor the same with an uppercase first character.

(NB: just renamed `User_id` to `Userid`)

**Comment by paurkedal** [comment]
I think un-camel-casing is okay, it's a simple reversible rule.  I also the RFC 4519 enumerates the required attributes. There are quite many, but at least a finite number, which means we don't need to consider an unlimited amount.  I'll take a brief look through them.

**Comment by paurkedal** [comment]
I don't see any unsupported ones which I recall seeing in a certificate, but I should note that I mostly work with DNs from WLCG/ITGF CAs and the Terena CA which I mentioned earlier.

**Comment by hannesm** [comment]
@paurkedal thanks! that's fine, I suspect once someone comes along trying to implement a real LDAP server we'll need to extend the list ;)

**Comment by paurkedal** [comment]
I think the hard requirement are those listed in RFC 4514 section 3, which are already covered.

**Comment by hannesm** [comment]
yes, and https://tools.ietf.org/html/rfc5280#page-21 are also implemented

**Comment by hannesm** [comment]
hmm, looking at OpenSSL, they write `street = ...`, while this PR outputs `STREET = ...` -- do you know whether there's a standard for that (I now assume that only abbreviations are all-uppercase, and thus would instead of `STREET` use `street` - WDYT?)

**Comment by paurkedal** [comment]
I think this is a more general difference: LDAP also writes `dc`, `cn`, `ou`, etc. while OpenSSL capitalizes them. At least OpenLDAP treats them as case-insensitive when input.

**Comment by paurkedal** [comment]
I can see in a list of certificate DNs that the one and two letter attribute types are all uppercased. The only longer attribute type in the list is `Email` which is only capitalized. I don't have any example for street.

**Pull request merged**
