### PR TITLE
Another attempt to implement pkcs12

### PR DESCRIPTION
**Pull request by NightBlues**
I wanted to implement basic use-case of pkcs12 - ability to pack cert and key encrypted with password to a pfx file. Then @hannesm showed me https://github.com/mirleft/ocaml-x509/pull/114 but it seems to be outdated. I'm not sure this PR should be merged, but may be it should be left for history purpose.

### CODE REVIEW

**Comment by NightBlues** [comment]
I've taken key and cert and created p12 container with openssl command:
`openssl pkcs12 -export -inkey KEY.key -in CERT.crt -out 1.p12 -passout pass:`
And got pkcs12 pfx file 1.p12 that I analized by hand (I have no schemes for all required bunch of pkcs standards). The file looks like this:

```
PFX
  version
  authSafe ContentInfo
    ContentType data { pkcs-7 1 }
    [0] content
      AuthenticatedSafe (octet string)
  macData
    mac         DigestInfo
      digestAlgorithm DigestAlgorithmIdentifier
        sha1 = base 1 3 <| 14 <| 3 <| 2 <| 26 (2B0E03021A)
        null
      Digest (octet string)
    macSalt (8 bytes)
    iteractions (=2048)
```

```
AuthenticatedSafe:
  ContentInfo
    encryptedData OBJECT IDENTIFIER ::= { pkcs-7 6 }
    [0] content
      EncryptedData 
        version
        encryptedContentInfo
          ContentType data { pkcs-7 1 }
          ContentEncryptionAlgorithmIdentifier
            pbewithSHAAnd40BitRC2-CBC ::= {pkcs-12PbeIds 6}
            parameters
              8 bytes salt
              iteration (2048)
          EncryptedContent ::= OCTET STRING
  ContentInfo
    data OBJECT IDENTIFIER ::= { pkcs-7 1 }
    [0]
      SafeContents (octet string)
```

Second SafeContents is:

```
SafeContents
  SafeBag
    pkcs8ShroudedKeyBag
    [0] bagValue
      PKCS8ShroudedKeyBag ::= EncryptedPrivateKeyInfo
        encryptionAlgorithm  EncryptionAlgorithmIdentifier,
          pbeWithSHAAnd3-KeyTripleDES-CBC
          params
            salt (8 bytes)
            iterations (=2048)
        encryptedData EncryptedData
        
    bagAttributes
      PKCS12Attribute
        attrId, OBJECT IDENTIFIER { pkcs9 0x15 } (localKeyId)
        attrValues
          octet string (actually sha1 of cert)
```

**Comment by hannesm** [comment]
I'm not entirely sure what to do here. I just spent some time to rebase #114 on top of current master -- does this work for you? (It feels easier to me to revise / improve 114 than to review this PR which takes some code from 114, and adds some other code).

Certainly, before merging 114, test cases and looking at deficiencies would be nice to do. Of course, in case this PR adds more functionality (or in a cleaner way), please tell and I'll have a more in-depth look (though reviewing may take some time).

**Comment by NightBlues** [comment]
> I just spent some time to rebase #114 on top of current master -- does this work for you?

@hannesm that's awesome! I've sent PR to your p12 branch moving some code i need from this PR (https://github.com/hannesm/ocaml-x509/pull/1)

**Comment by hannesm** [comment]
Thanks @NightBlues

**Pull request closed without merging**
