### PR TITLE
Hammertime

### PR DESCRIPTION
**Pull request by pqwy**
On top of #90 -- pervasively use `ptime`.

### CODE REVIEW

**Comment by hannesm** [comment]
looks good to me.  is this ready from your side?

**Comment by pqwy** [comment]
Aha

**Comment by hannesm** [comment]
(I extended my wishlist in https://github.com/mirleft/ocaml-asn1-combinators/issues/17)

**Comment by hannesm** [comment]
I rebased this onto master as #97

**Pull request closed without merging**
