### PR TITLE
use Cstruct.length instead of deprecated Cstruct.len

### PR DESCRIPTION
**Pull request by hannesm**
requires cstruct 6.0.0

### CODE REVIEW

**Comment by pukkamustard** [comment]
Is there an ETA for a 0.15.0 release that contains this?

**Comment by hannesm** [comment]
No, is this urgent for you? Since it is only a deprecation warning, I intended to wait with the next release until some more bugfixes/features are integrated. All existing opam-released packages should compile fine (warnings are not errors, unless in development mode).

**Comment by pukkamustard** [comment]
Not urgent. I'm packaging some OCaml packages for Guix. As long as we keep Cstruct at 4.0.0 it should be ok.

> All existing opam-released packages should compile fine (warnings are not errors, unless in development mode).

Hm, true. Guix build with Cstruct 6.0.0 failed because of the deprecation warning. I will investigate why.

**Comment by pukkamustard** [comment]
Your comment led to a minor improvement for all OCaml packages in Guix (https://issues.guix.gnu.org/49868). Thanks!

**Comment by hannesm** [comment]
I also cut a release (0.14.1) at https://github.com/ocaml/opam-repository/pull/19203 :)

**Pull request merged**
