### PR TITLE
Travis: enable the OS X build.

### PR DESCRIPTION
**Pull request by yallop**

### CODE REVIEW

**Comment by yallop** [comment]
This may fail before #83 is merged.

**Comment by yallop** [comment]
This might pass if the build is restarted.

**Comment by hannesm** [comment]
you'll need to rebase this to have travis using the patch from #83.

**Comment by yallop** [comment]
Travis usually tests pull requests by merging the branch into master.  (But I've rebased anyway.)

**Comment by hannesm** [comment]
thanks!

**Pull request merged**
